In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact,addicted_label
0,0,24.0,NaN,1.83,1.59,2.11,7.46,122.0,38.0,8.63,Male,Medium,No,1
1,1,19.0,5.97,1.08,NaN,3.03,8.22,76.0,19.0,NaN,Female,Medium,No,0
2,2,18.0,5.09,NaN,NaN,NaN,6.25,134.0,60.0,7.47,Female,Low,Yes,0
3,3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66,Other,Low,NaN,1
4,4,26.0,11.20,1.87,2.81,1.95,5.25,NaN,NaN,13.39,Female,Medium,No,1

In [4]:
df

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact,addicted_label
0,0,24.0,NaN,1.83,1.59,2.11,7.46,122.0,38.0,8.63,Male,Medium,No,1
1,1,19.0,5.97,1.08,NaN,3.03,8.22,76.0,19.0,NaN,Female,Medium,No,0
2,2,18.0,5.09,NaN,NaN,NaN,6.25,134.0,60.0,7.47,Female,Low,Yes,0
3,3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66,Other,Low,NaN,1
4,4,26.0,11.20,1.87,2.81,1.95,5.25,NaN,NaN,13.39,Female,Medium,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691364,691364,22.0,10.78,3.25,1.57,1.65,7.71,86.0,94.0,12.89,Male,NaN,No,1
691365,691365,20.0,3.45,1.86,0.89,0.30,6.59,221.0,42.0,8.47,Female,High,No,1
691366,691366,NaN,NaN,NaN,NaN,2.06,6.16,NaN,86.0,7.79,Other,Medium,No,1
691367,691367,22.0,11.78,3.69,0.23,1.35,5.53,171.0,62.0,7.71,Other,NaN,NaN,1
691368,691368,21.0,5.64,1.03,3.05,1.01,4.91,169.0,NaN,9.47,Other,Medium,Yes,0

In [5]:
df.columns.tolist()

['id',
 'age',
 'daily_screen_time_hours',
 'social_media_hours',
 'gaming_hours',
 'work_study_hours',
 'sleep_hours',
 'notifications_per_day',
 'app_opens_per_day',
 'weekend_screen_time',
 'gender',
 'stress_level',
 'academic_work_impact',
 'addicted_label']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       691369 non-null  int64
 1   age                      662440 non-null  float64
 2   daily_screen_time_hours  595515 non-null  float64
 3   social_media_hours       557374 non-null  float64
 4   gaming_hours             564548 non-null  float64
 5   work_study_hours         639851 non-null  float64
 6   sleep_hours              646889 non-null  float64
 7   notifications_per_day    623785 non-null  float64
 8   app_opens_per_day        610659 non-null  float64
 9   weekend_screen_time      579306 non-null  float64
 10  gender                   662335 non-null  object
 11  stress_level             636221 non-null  object
 12  academic_work_impact     647145 non-null  object
 13  addicted_label           691369 non-null  int64
dtypes: float64(9), int64(2), object(3)
memory usage: 73.8+ MB

In [7]:
df["gender"].value_counts()

gender
Male      223662
Female    221595
Other     217078
Name: count, dtype: int64

In [8]:
def category_value_count(cat_column_list):
 print("\n" + "-"*30)   
 for col in cat_column_list: 
     print(df[col].value_counts())
     print("\n" + "-"*30)
     
category_value_count(df.select_dtypes(include="object").columns.tolist())

------------------------------
gender
Male      223662
Female    221595
Other     217078
Name: count, dtype: int64

------------------------------
stress_level
High      220873
Low       207783
Medium    207565
Name: count, dtype: int64

------------------------------
academic_work_impact
Yes    330566
No     316579
Name: count, dtype: int64

------------------------------

In [9]:
corr_matrix = df.corr(numeric_only=True)

In [10]:
corr_matrix["addicted_label"].sort_values(ascending=False)

addicted_label             1.000000
daily_screen_time_hours    0.611398
weekend_screen_time        0.589903
social_media_hours         0.532409
work_study_hours           0.251416
gaming_hours               0.205283
app_opens_per_day          0.063482
sleep_hours                0.042545
age                        0.004043
id                         0.001097
notifications_per_day     -0.011583
Name: addicted_label, dtype: float64

In [11]:
removed_label = df["addicted_label"].copy()
df = df.drop(["addicted_label" , "id"], axis = 1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      662440 non-null  float64
 1   daily_screen_time_hours  595515 non-null  float64
 2   social_media_hours       557374 non-null  float64
 3   gaming_hours             564548 non-null  float64
 4   work_study_hours         639851 non-null  float64
 5   sleep_hours              646889 non-null  float64
 6   notifications_per_day    623785 non-null  float64
 7   app_opens_per_day        610659 non-null  float64
 8   weekend_screen_time      579306 non-null  float64
 9   gender                   662335 non-null  object
 10  stress_level             636221 non-null  object
 11  academic_work_impact     647145 non-null  object
dtypes: float64(9), object(3)
memory usage: 63.3+ MB

In [13]:
# Method 1 of finding Missing Percentage
(df.isnull().sum()*100)/(df.count() + df.isnull().sum())

age                         4.184307
daily_screen_time_hours    13.864376
social_media_hours         19.381112
gaming_hours               18.343461
work_study_hours            7.451592
sleep_hours                 6.433612
notifications_per_day       9.775388
app_opens_per_day          11.673940
weekend_screen_time        16.208855
gender                      4.199494
stress_level                7.976638
academic_work_impact        6.396584
dtype: float64

In [14]:
# Method 2 of finding Missing Percentage => pandas treat isnull() as 0 n 1 so means adds 0 + 1 / total no of values 
df.isnull().mean()*100

age                         4.184307
daily_screen_time_hours    13.864376
social_media_hours         19.381112
gaming_hours               18.343461
work_study_hours            7.451592
sleep_hours                 6.433612
notifications_per_day       9.775388
app_opens_per_day          11.673940
weekend_screen_time        16.208855
gender                      4.199494
stress_level                7.976638
academic_work_impact        6.396584
dtype: float64

## MISSING VALUE

In [15]:
from sklearn.impute import SimpleImputer
imputer_mean = SimpleImputer(strategy="mean")
imputer_median = SimpleImputer(strategy="median")

##### Numerical dataset

In [16]:
df_num = df.drop(df.select_dtypes(include="object").columns.tolist() , axis = 1)
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      662440 non-null  float64
 1   daily_screen_time_hours  595515 non-null  float64
 2   social_media_hours       557374 non-null  float64
 3   gaming_hours             564548 non-null  float64
 4   work_study_hours         639851 non-null  float64
 5   sleep_hours              646889 non-null  float64
 6   notifications_per_day    623785 non-null  float64
 7   app_opens_per_day        610659 non-null  float64
 8   weekend_screen_time      579306 non-null  float64
dtypes: float64(9)
memory usage: 47.5 MB

imputer_mean.fit(df_num)

In [17]:
#imputer_mean.fit(df_num)

In [18]:
#imputer_mean.statistics_

In [19]:
#Y = imputer_mean.transform(df_num)
#df_mean = pd.DataFrame(Y, columns=df_num.columns,index=df_num.index)

In [20]:
#df_mean.head()

In [21]:
#df_mean.isnull().sum().sum()

In [22]:
#imputer_median.fit(df_num)

In [23]:
#X = imputer_median.transform(df_num)
#df_median = pd.DataFrame(X, columns=df_num.columns,
#                          index=df_num.index)

In [24]:
#df_median.head()

In [25]:
#df_median.isnull().sum().sum()

In [26]:
#imputer_median.statistics_

##### Categorical dataset

In [27]:
df_cat = df[df.select_dtypes(include="object").columns.tolist()]
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 3 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   gender                662335 non-null  object
 1   stress_level          636221 non-null  object
 2   academic_work_impact  647145 non-null  object
dtypes: object(3)
memory usage: 15.8+ MB

In [28]:
df_cat.isnull().sum().sum()

128406

In [29]:
#imputer_mode = SimpleImputer(strategy="most_frequent")

In [30]:
#Y =imputer_mode.fit_transform(df_cat)
#df_cat = pd.DataFrame(Y, columns=df_cat.columns,index=df_cat.index)

In [31]:
#df_cat

In [32]:
#df_cat.isnull().sum().sum()

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

onehot_cols = [
    "gender",
    "academic_work_impact"
]

ordinal_cols = [
    "stress_level"
]

onehot_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore" , sparse_output=False))
])

ordinal_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(
        categories=[["low", "Medium", "High"]],
        handle_unknown="use_encoded_value",
        unknown_value=-1
        
    ))
])

preprocessor = ColumnTransformer([
    ("onehot", onehot_pipeline, onehot_cols),
    ("ordinal", ordinal_pipeline, ordinal_cols)
], remainder="drop")

In [34]:
#Z = preprocessor.fit_transform(df_cat)

In [35]:
#Z

In [36]:
#cat_encoded_df = pd.DataFrame(
 #   Z,
  #  columns=preprocessor.get_feature_names_out(),
 #   index=df_cat.index
#)

In [37]:
#cat_encoded_df

In [38]:
#final_mean_df = pd.concat(
  #  [df_mean ,cat_encoded_df],
 #   axis=1
#)

In [39]:
#final_median_df = pd.concat(
 #   [df_median,cat_encoded_df],
  #  axis=1
#)

In [40]:
#final_mean_df.describe()

In [41]:
#final_median_df.describe()

In [42]:
#final_median_df

#### Feature Enginnering

In [43]:
import numpy as np

def create_features(df):
    df = df.copy()

    screen = df["daily_screen_time_hours"].clip(lower=1e-6)
    sleep = df["sleep_hours"].clip(lower=1e-6)
    opens = df["app_opens_per_day"].clip(lower=1e-6)

    # Combined usage
    df["leisure_screen_hours"] = (
        df["social_media_hours"] +
        df["gaming_hours"]
    )

    # Screen-time composition
    df["social_media_share"] = (
        df["social_media_hours"] / screen
    )

    df["gaming_share"] = (
        df["gaming_hours"] / screen
    )

    df["leisure_screen_share"] = (
        df["leisure_screen_hours"] / screen
    )

    # Weekend behaviour
    df["weekend_screen_change"] = (
        df["weekend_screen_time"] -
        df["daily_screen_time_hours"]
    )

    df["weekend_screen_ratio"] = (
        df["weekend_screen_time"] / screen
    )

    # Digital-life balance
    df["screen_sleep_ratio"] = (
        df["daily_screen_time_hours"] / sleep
    )

    df["screen_sleep_difference"] = (
        df["daily_screen_time_hours"] -
        df["sleep_hours"]
    )

    # Usage intensity
    df["notifications_per_screen_hour"] = (
        df["notifications_per_day"] / screen
    )

    df["app_opens_per_screen_hour"] = (
        df["app_opens_per_day"] / screen
    )

    df["notifications_per_app_open"] = (
        df["notifications_per_day"] / opens
    )

    return df.replace([np.inf, -np.inf], np.nan)

In [44]:
#mean_df_prepared = create_features(final_mean_df)

In [45]:
#mean_df_prepared.head()

In [46]:
#mean_df_prepared.isnull().sum().sum()

In [47]:
#median_df_prepared = create_features(final_median_df) 
#median_df_prepared.head()

In [48]:
#median_df_prepared.isnull().sum().sum()

In [49]:
import matplotlib.pyplot as plt
import seaborn as sns

def heat(df):
# Keep only numeric columns
 numeric_data = df.select_dtypes(include="number")

 correlation_matrix = numeric_data.corr()

 plt.figure(figsize=(18, 12))

 mask = np.triu(
    np.ones_like(correlation_matrix, dtype=bool)
 )

 sns.heatmap(
    correlation_matrix,
    mask=mask,
    cmap="coolwarm",
    center=0,
    vmin=-1,
    vmax=1,
    annot=False
 )

 plt.title("Feature Correlation Heatmap")
 plt.show()

In [50]:
#heat(mean_df_prepared)

In [51]:
#heat(median_df_prepared)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      662440 non-null  float64
 1   daily_screen_time_hours  595515 non-null  float64
 2   social_media_hours       557374 non-null  float64
 3   gaming_hours             564548 non-null  float64
 4   work_study_hours         639851 non-null  float64
 5   sleep_hours              646889 non-null  float64
 6   notifications_per_day    623785 non-null  float64
 7   app_opens_per_day        610659 non-null  float64
 8   weekend_screen_time      579306 non-null  float64
 9   gender                   662335 non-null  object
 10  stress_level             636221 non-null  object
 11  academic_work_impact     647145 non-null  object
dtypes: float64(9), object(3)
memory usage: 63.3+ MB

In [53]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      662440 non-null  float64
 1   daily_screen_time_hours  595515 non-null  float64
 2   social_media_hours       557374 non-null  float64
 3   gaming_hours             564548 non-null  float64
 4   work_study_hours         639851 non-null  float64
 5   sleep_hours              646889 non-null  float64
 6   notifications_per_day    623785 non-null  float64
 7   app_opens_per_day        610659 non-null  float64
 8   weekend_screen_time      579306 non-null  float64
dtypes: float64(9)
memory usage: 47.5 MB

In [54]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 3 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   gender                662335 non-null  object
 1   stress_level          636221 non-null  object
 2   academic_work_impact  647145 non-null  object
dtypes: object(3)
memory usage: 15.8+ MB

## Data Cleaning Complete Pipeline

In [55]:
from sklearn import set_config
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.impute import SimpleImputer

set_config(transform_output="pandas")

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(
        strategy="median",
        add_indicator=False
     )),
    ("feature_engineering", FunctionTransformer(
        create_features,
        validate=False
    ))
])

In [56]:
num_attribs = list(df_num)
cat_attribs = list(df_cat)

pre_processor = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", preprocessor , cat_attribs )
    ])

In [57]:
#x = full_pipeline.fit_transform(df)

In [58]:
#x.info()

In [59]:
#x

#### Cross Validation

In [62]:
from catboost import CatBoostClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

catboost_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=7,
    loss_function="Logloss",
    eval_metric="AUC",
    random_seed=42,
    verbose=False,
    thread_count=-1,
    allow_writing_files=False
)

catboost_pipeline = Pipeline([
    ("preprocessing",  pre_processor),
    ("model", catboost_model)
])

In [63]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    catboost_pipeline,
    df,               
    removed_label,
    cv=cv,
    scoring="roc_auc",
    n_jobs=1
)

print("Fold scores:", scores)
print("Mean ROC-AUC:", scores.mean())
print("Standard deviation:", scores.std())

Fold scores: [0.95225986 0.95310644 0.95376981 0.95433225 0.95316109]
Mean ROC-AUC: 0.9533258910556647
Standard deviation: 0.0006959253566607721

In [64]:
from sklearn.model_selection import RandomizedSearchCV

param_distributions = {
    # Preprocessing choice
    "preprocessing__num__imputer__strategy": [
        "mean",
        "median"
    ],

    # CatBoost parameters
    "model__iterations": [
        300, 500, 800, 1200
    ],

    "model__learning_rate": [
        0.02, 0.05, 0.1
    ],

    "model__depth": [
        5, 6, 7, 8, 10
    ],

    "model__l2_leaf_reg": [
        3, 5, 10, 20
    ],

    "model__random_strength": [
        0, 0.5, 1, 2
    ]
}

In [65]:
search = RandomizedSearchCV(
    estimator=catboost_pipeline,
    param_distributions=param_distributions,
    n_iter=15,
    scoring="roc_auc",
    cv=cv,
    random_state=42,
    n_jobs=1,
    verbose=1,
    refit=True
)

search.fit(df, removed_label)

Fitting 5 folds for each of 15 candidates, totalling 75 fits

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('feature_engineering',
                                                                                                FunctionTransformer(func=<function create_features at 0x0000020B22E89620>))]),
                                                                               ['age',
                                                                                'daily_screen_time_hour...
                                              <catboost.core.CatBoostClassifier object at 0x0000020B46CC7380>)]),
                   n_iter=15, n_jobs=1,
                   param_distributions={'model__depth': [5, 6, 7, 8, 10],
                                        'model__iterations': [300, 500, 800,
                                                              1200],
                                        'model__l2_leaf_reg': [3, 5, 10, 20],
                                        'model__learning_rate': [0.02, 0.05,
                                                                 0.1],
                                        'model__random_strength': [0, 0.5, 1,
                                                                   2],
                                        'preprocessing__num__imputer__strategy': ['mean',
                                                                                  'median']},
                   random_state=42, scoring='roc_auc', verbose=1)

In [66]:
print("Best ROC-AUC:", search.best_score_)
print("Best parameters:", search.best_params_)

Best ROC-AUC: 0.9624739993355093
Best parameters: {'preprocessing__num__imputer__strategy': 'mean', 'model__random_strength': 0.5, 'model__learning_rate': 0.1, 'model__l2_leaf_reg': 5, 'model__iterations': 1200, 'model__depth': 8}

In [67]:
best_pipeline = search.best_estimator_

## MULTIPLE MODEL PIPELINE

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from catboost import CatBoostClassifier

model_pipelines = {
    "logistic_regression": Pipeline([
        ("preprocessing", pre_processor),
        ("model", LogisticRegression(max_iter=2000))
    ]),

    "random_forest": Pipeline([
        ("preprocessing", pre_processor),
        ("model", RandomForestClassifier(
            random_state=42,
            n_jobs=-1
        ))
    ]),

    "extra_trees": Pipeline([
        ("preprocessing", pre_processor),
        ("model", ExtraTreesClassifier(
            random_state=42,
            n_jobs=-1
        ))
    ]),

    "catboost": Pipeline([
        ("preprocessing", pre_processor),
        ("model", CatBoostClassifier(
            random_seed=42,
            eval_metric="AUC",
            verbose=False,
            thread_count=-1,
            allow_writing_files=False
        ))
    ])
}

In [ ]:
search_spaces = {
    "logistic_regression": {
        "preprocessing__num__imputer__strategy": [
            "mean", "median"
        ],
        "model__C": [
            0.01, 0.1, 1, 10, 100
        ],
        "model__class_weight": [
            None, "balanced"
        ]
    },

    "random_forest": {
        "preprocessing__num__imputer__strategy": [
            "mean", "median"
        ],
        "model__n_estimators": [
            200, 400, 600
        ],
        "model__max_depth": [
            None, 10, 20, 30
        ],
        "model__min_samples_leaf": [
            1, 2, 5
        ],
        "model__max_features": [
            "sqrt", "log2", None
        ]
    },

    "extra_trees": {
        "preprocessing__num__imputer__strategy": [
            "mean", "median"
        ],
        "model__n_estimators": [
            200, 400, 600
        ],
        "model__max_depth": [
            None, 10, 20, 30
        ],
        "model__min_samples_leaf": [
            1, 2, 5
        ],
        "model__max_features": [
            "sqrt", "log2", None
        ]
    },

    "catboost": {
        "preprocessing__num__imputer__strategy": [
            "mean", "median"
        ],
        "model__iterations": [
            300, 500, 800, 1200
        ],
        "model__learning_rate": [
            0.02, 0.05, 0.1
        ],
        "model__depth": [
            5, 6, 7, 8, 10
        ],
        "model__l2_leaf_reg": [
            3, 5, 10, 20
        ],
        "model__random_strength": [
            0, 0.5, 1, 2
        ]
    }
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

search_results = {}

for name in model_pipelines:

    print(f"Searching: {name}")

    search = RandomizedSearchCV(
        estimator=model_pipelines[name],
        param_distributions=search_spaces[name],
        n_iter=15,
        scoring="roc_auc",
        cv=cv,
        random_state=42,
        n_jobs=1,
        verbose=1,
        refit=True
    )

    search.fit(df, removed_label)

    search_results[name] = search

    print(f"Best ROC-AUC for {name}: {search.best_score_}")
    print(f"Best parameters: {search.best_params_}")

In [ ]:
best_model_name = max(
    search_results,
    key=lambda name: search_results[name].best_score_
)

best_search = search_results[best_model_name]
best_pipeline = best_search.best_estimator_

print("Overall best model:", best_model_name)
print("Best ROC-AUC:", best_search.best_score_)
print("Best parameters:", best_search.best_params_)