In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact,addicted_label
0,0,24.0,NaN,1.83,1.59,2.11,7.46,122.0,38.0,8.63,Male,Medium,No,1
1,1,19.0,5.97,1.08,NaN,3.03,8.22,76.0,19.0,NaN,Female,Medium,No,0
2,2,18.0,5.09,NaN,NaN,NaN,6.25,134.0,60.0,7.47,Female,Low,Yes,0
3,3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66,Other,Low,NaN,1
4,4,26.0,11.20,1.87,2.81,1.95,5.25,NaN,NaN,13.39,Female,Medium,No,1

In [4]:
df

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact,addicted_label
0,0,24.0,NaN,1.83,1.59,2.11,7.46,122.0,38.0,8.63,Male,Medium,No,1
1,1,19.0,5.97,1.08,NaN,3.03,8.22,76.0,19.0,NaN,Female,Medium,No,0
2,2,18.0,5.09,NaN,NaN,NaN,6.25,134.0,60.0,7.47,Female,Low,Yes,0
3,3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66,Other,Low,NaN,1
4,4,26.0,11.20,1.87,2.81,1.95,5.25,NaN,NaN,13.39,Female,Medium,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691364,691364,22.0,10.78,3.25,1.57,1.65,7.71,86.0,94.0,12.89,Male,NaN,No,1
691365,691365,20.0,3.45,1.86,0.89,0.30,6.59,221.0,42.0,8.47,Female,High,No,1
691366,691366,NaN,NaN,NaN,NaN,2.06,6.16,NaN,86.0,7.79,Other,Medium,No,1
691367,691367,22.0,11.78,3.69,0.23,1.35,5.53,171.0,62.0,7.71,Other,NaN,NaN,1
691368,691368,21.0,5.64,1.03,3.05,1.01,4.91,169.0,NaN,9.47,Other,Medium,Yes,0

In [5]:
df.columns.tolist()

['id',
 'age',
 'daily_screen_time_hours',
 'social_media_hours',
 'gaming_hours',
 'work_study_hours',
 'sleep_hours',
 'notifications_per_day',
 'app_opens_per_day',
 'weekend_screen_time',
 'gender',
 'stress_level',
 'academic_work_impact',
 'addicted_label']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       691369 non-null  int64
 1   age                      662440 non-null  float64
 2   daily_screen_time_hours  595515 non-null  float64
 3   social_media_hours       557374 non-null  float64
 4   gaming_hours             564548 non-null  float64
 5   work_study_hours         639851 non-null  float64
 6   sleep_hours              646889 non-null  float64
 7   notifications_per_day    623785 non-null  float64
 8   app_opens_per_day        610659 non-null  float64
 9   weekend_screen_time      579306 non-null  float64
 10  gender                   662335 non-null  object
 11  stress_level             636221 non-null  object
 12  academic_work_impact     647145 non-null  object
 13  addicted_label           691369 non-null  int64
dtypes: float64(9), int64(2), object(3)
memory usage: 73.8+ MB

In [7]:
df["gender"].value_counts()

gender
Male      223662
Female    221595
Other     217078
Name: count, dtype: int64

In [8]:
def category_value_count(cat_column_list):
 print("\n" + "-"*30)   
 for col in cat_column_list: 
     print(df[col].value_counts())
     print("\n" + "-"*30)
     
category_value_count(df.select_dtypes(include="object").columns.tolist())

------------------------------
gender
Male      223662
Female    221595
Other     217078
Name: count, dtype: int64

------------------------------
stress_level
High      220873
Low       207783
Medium    207565
Name: count, dtype: int64

------------------------------
academic_work_impact
Yes    330566
No     316579
Name: count, dtype: int64

------------------------------

In [9]:
df.describe()

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addicted_label
count,691369.000000,662440.000000,595515.000000,557374.000000,564548.000000,639851.000000,646889.000000,623785.000000,610659.000000,579306.000000,691369.000000
mean,345684.000000,26.615408,7.640865,2.471038,1.459265,2.366971,6.804334,145.894900,102.636781,9.479866,0.709424
std,199581.183467,5.153162,2.721446,1.316137,0.934552,1.258797,1.234512,65.917556,48.093970,2.856006,0.454028
min,0.000000,18.000000,0.500000,0.000000,0.000000,0.000000,4.500000,20.000000,15.000000,0.510000,0.000000
25%,172842.000000,22.000000,5.480000,1.450000,0.700000,1.360000,5.780000,93.000000,64.000000,7.280000,0.000000
50%,345684.000000,27.000000,7.770000,2.310000,1.330000,2.200000,6.800000,150.000000,104.000000,9.580000,1.000000
75%,518526.000000,31.000000,9.840000,3.370000,2.090000,3.200000,7.870000,204.000000,145.000000,11.750000,1.000000
max,691368.000000,35.000000,15.000000,8.000000,4.000000,6.000000,9.000000,250.000000,180.000000,17.560000,1.000000

In [10]:
corr_matrix = df.corr(numeric_only=True)

In [11]:
corr_matrix["addicted_label"].sort_values(ascending=False)

addicted_label             1.000000
daily_screen_time_hours    0.611398
weekend_screen_time        0.589903
social_media_hours         0.532409
work_study_hours           0.251416
gaming_hours               0.205283
app_opens_per_day          0.063482
sleep_hours                0.042545
age                        0.004043
id                         0.001097
notifications_per_day     -0.011583
Name: addicted_label, dtype: float64

In [12]:
df = df.drop("addicted_label", axis = 1)

In [13]:
df = df.drop("id", axis = 1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      662440 non-null  float64
 1   daily_screen_time_hours  595515 non-null  float64
 2   social_media_hours       557374 non-null  float64
 3   gaming_hours             564548 non-null  float64
 4   work_study_hours         639851 non-null  float64
 5   sleep_hours              646889 non-null  float64
 6   notifications_per_day    623785 non-null  float64
 7   app_opens_per_day        610659 non-null  float64
 8   weekend_screen_time      579306 non-null  float64
 9   gender                   662335 non-null  object
 10  stress_level             636221 non-null  object
 11  academic_work_impact     647145 non-null  object
dtypes: float64(9), object(3)
memory usage: 63.3+ MB

In [15]:
# Method 1 of finding Missing Percentage
(df.isnull().sum()*100)/(df.count() + df.isnull().sum())

age                         4.184307
daily_screen_time_hours    13.864376
social_media_hours         19.381112
gaming_hours               18.343461
work_study_hours            7.451592
sleep_hours                 6.433612
notifications_per_day       9.775388
app_opens_per_day          11.673940
weekend_screen_time        16.208855
gender                      4.199494
stress_level                7.976638
academic_work_impact        6.396584
dtype: float64

In [16]:
# Method 2 of finding Missing Percentage => pandas treat isnull() as 0 n 1 so means adds 0 + 1 / total no of values 
df.isnull().mean()*100

age                         4.184307
daily_screen_time_hours    13.864376
social_media_hours         19.381112
gaming_hours               18.343461
work_study_hours            7.451592
sleep_hours                 6.433612
notifications_per_day       9.775388
app_opens_per_day          11.673940
weekend_screen_time        16.208855
gender                      4.199494
stress_level                7.976638
academic_work_impact        6.396584
dtype: float64

## MISSING VALUE

In [17]:
from sklearn.impute import SimpleImputer
imputer_mean = SimpleImputer(strategy="mean")
imputer_median = SimpleImputer(strategy="median")

##### Numerical dataset

In [18]:
df_num = df.drop(df.select_dtypes(include="object").columns.tolist() , axis = 1)
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      662440 non-null  float64
 1   daily_screen_time_hours  595515 non-null  float64
 2   social_media_hours       557374 non-null  float64
 3   gaming_hours             564548 non-null  float64
 4   work_study_hours         639851 non-null  float64
 5   sleep_hours              646889 non-null  float64
 6   notifications_per_day    623785 non-null  float64
 7   app_opens_per_day        610659 non-null  float64
 8   weekend_screen_time      579306 non-null  float64
dtypes: float64(9)
memory usage: 47.5 MB

imputer_mean.fit(df_num)

In [19]:
imputer_mean.fit(df_num)

SimpleImputer()

In [20]:
imputer_mean.statistics_

array([ 26.61540819,   7.64086549,   2.47103821,   1.45926472,
         2.3669709 ,   6.8043341 , 145.89489968, 102.63678092,
         9.47986644])

In [38]:
Y = imputer_mean.transform(df_num)
df_mean = pd.DataFrame(Y, columns=df_num.columns,index=df_num.index)

In [46]:
df_mean.head()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time
0,24.0,7.640865,1.830000,1.590000,2.110000,7.46,122.0000,38.000000,8.630000
1,19.0,5.970000,1.080000,1.459265,3.030000,8.22,76.0000,19.000000,9.479866
2,18.0,5.090000,2.471038,1.459265,2.366971,6.25,134.0000,60.000000,7.470000
3,21.0,6.420000,1.260000,1.420000,3.360000,8.85,112.0000,94.000000,8.660000
4,26.0,11.200000,1.870000,2.810000,1.950000,5.25,145.8949,102.636781,13.390000

In [44]:
df_mean.isnull().sum().sum()

0

In [42]:
imputer_median.fit(df_num)

SimpleImputer(strategy='median')

In [34]:
df_median = pd.DataFrame(X, columns=df_num.columns,
                          index=df_num.index)

In [47]:
df_median.head()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time
0,24.0,7.77,1.83,1.59,2.11,7.46,122.0,38.0,8.63
1,19.0,5.97,1.08,1.33,3.03,8.22,76.0,19.0,9.58
2,18.0,5.09,2.31,1.33,2.20,6.25,134.0,60.0,7.47
3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66
4,26.0,11.20,1.87,2.81,1.95,5.25,150.0,104.0,13.39

In [36]:
df_median.isnull().sum().sum()

0

In [37]:
imputer_median.statistics_

array([ 27.  ,   7.77,   2.31,   1.33,   2.2 ,   6.8 , 150.  , 104.  ,
         9.58])

##### Categorical dataset

In [51]:
df_cat = df[df.select_dtypes(include="object").columns.tolist()]
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 3 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   gender                662335 non-null  object
 1   stress_level          636221 non-null  object
 2   academic_work_impact  647145 non-null  object
dtypes: object(3)
memory usage: 15.8+ MB

In [54]:
df_cat.isnull().sum().sum()

128406

In [58]:
imputer_mode = SimpleImputer(strategy="most_frequent")

In [67]:
Y =imputer_mode.fit_transform(df_cat)
df_cat = pd.DataFrame(Y, columns=df_cat.columns,index=df_cat.index)

In [70]:
df_cat

        gender stress_level academic_work_impact
0         Male       Medium                   No
1       Female       Medium                   No
2       Female          Low                  Yes
3        Other          Low                  Yes
4       Female       Medium                   No
...        ...          ...                  ...
691364    Male         High                   No
691365  Female         High                   No
691366   Other       Medium                   No
691367   Other         High                  Yes
691368   Other       Medium                  Yes

[691369 rows x 3 columns]

In [71]:
df_cat.isnull().sum().sum()

0

In [91]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

onehot_cols = [
    "gender",
    "academic_work_impact"
]

ordinal_cols = [
    "stress_level"
]

onehot_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore" , sparse_output=False))
])

ordinal_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(
        categories=[["low", "medium", "high"]],
        handle_unknown="use_encoded_value",
        unknown_value=-1
        
    ))
])

preprocessor = ColumnTransformer([
    ("onehot", onehot_pipeline, onehot_cols),
    ("ordinal", ordinal_pipeline, ordinal_cols)
], remainder="passthrough")

In [93]:
Z = preprocessor.fit_transform(df_cat)

In [94]:
Z

array([[ 0.,  1.,  0.,  1.,  0., -1.],
       [ 1.,  0.,  0.,  1.,  0., -1.],
       [ 1.,  0.,  0.,  0.,  1., -1.],
       ...,
       [ 0.,  0.,  1.,  1.,  0., -1.],
       [ 0.,  0.,  1.,  0.,  1., -1.],
       [ 0.,  0.,  1.,  0.,  1., -1.]])

In [95]:
df_cat_fixed = pd.DataFrame(Z, columns=df_cat.columns,index=df_cat.index)

ValueError: Shape of passed values is (691369, 6), indices imply (691369, 3)

0